# 01 - Exploration des 3 sources de données

Objectif de ce notebook : comprendre la structure, la période couverte et la qualité (valeurs manquantes) de chaque dataset, avant de penser feature engineering.

1. `results.csv` - historique des matchs internationaux (1872-2026)
2. `elo_ratings_wc2026.csv` - ratings Elo pré-tournoi pour les 48 qualifiés
3. `wc_2026_teams.csv` / `wc_2026_fixtures.csv` - équipes et calendrier 2026

In [11]:
import pandas as pd

pd.set_option('display.max_columns', None)

## 1. `results.csv` - historique des matchs

In [12]:
results = pd.read_csv("../data/raw/results.csv")
results.shape
results.head()
results.dtypes

date              str
home_team         str
away_team         str
home_score    float64
away_score    float64
tournament        str
city              str
country           str
neutral          bool
dtype: object

In [13]:
results.isna().sum()

date           0
home_team      0
away_team      0
home_score    13
away_score    13
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [14]:
results[results['home_score'].isna()]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49481,2026-06-30,Ivory Coast,Norway,NaN,NaN,FIFA World Cup,Arlington,United States,True
49482,2026-06-30,France,Sweden,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49483,2026-06-30,Mexico,Ecuador,NaN,NaN,FIFA World Cup,Mexico City,Mexico,False
49484,2026-07-01,England,DR Congo,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49485,2026-07-01,Belgium,Senegal,NaN,NaN,FIFA World Cup,Seattle,United States,True
49486,2026-07-01,United States,Bosnia and Herzegovina,NaN,NaN,FIFA World Cup,Santa Clara,United States,False
49487,2026-07-02,Spain,Austria,NaN,NaN,FIFA World Cup,Inglewood,United States,True
49488,2026-07-02,Portugal,Croatia,NaN,NaN,FIFA World Cup,Toronto,Canada,True
49489,2026-07-02,Switzerland,Algeria,NaN,NaN,FIFA World Cup,Vancouver,Canada,True
49490,2026-07-03,Australia,Egypt,NaN,NaN,FIFA World Cup,Arlington,United States,True
49491,2026-07-03,Argentina,Cape Verde,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49492,2026-07-03,Colombia,Ghana,NaN,NaN,FIFA World Cup,Kansas City,United States,True
49493,2026-07-04,Canada,Morocco,NaN,NaN,FIFA World Cup,Houston,United States,True

## 2. elo_ratings_wc2026.csv

In [15]:
elo = pd.read_csv("../data/raw/elo_ratings_wc2026.csv")
elo.shape

(4683, 23)

In [16]:
elo.head()

,year,snapshot_date,country,rank,country_code,rating,rank_max,rating_max,rank_avg,rating_avg,rank_min,rating_min,matches_total,matches_home,matches_away,matches_neutral,wins,losses,draws,goals_for,goals_against,confederation,is_host
0,1901,1901-12-31,England,1,EN,2013,1,2079,2,1989,2,1889,73,38,35,0,46,16,11,262,102,UEFA,0
1,1901,1901-12-31,Scotland,2,SQ,1973,1,2104,1,2018,2,1926,74,37,37,0,53,9,12,277,101,UEFA,0
2,1902,1902-12-31,Argentina,1,AR,2021,1,2021,1,2021,1,2021,1,0,1,0,1,0,0,6,0,CONMEBOL,0
3,1902,1902-12-31,England,2,EN,1995,1,2079,2,1989,2,1889,77,39,38,0,47,16,14,266,105,UEFA,0
4,1902,1902-12-31,Scotland,3,SQ,1983,1,2104,1,2017,3,1926,79,39,40,0,56,9,14,293,106,UEFA,0

In [17]:
latest_date = elo['snapshot_date'].max()
elo_latest = elo[elo['snapshot_date'] == latest_date]
elo_latest.shape

(48, 23)

In [18]:
elo_latest.isna().sum()

year               0
snapshot_date      0
country            0
rank               0
country_code       0
rating             0
rank_max           0
rating_max         0
rank_avg           0
rating_avg         0
rank_min           0
rating_min         0
matches_total      0
matches_home       0
matches_away       0
matches_neutral    0
wins               0
losses             0
draws              0
goals_for          0
goals_against      0
confederation      0
is_host            0
dtype: int64

## 3. wc_2026_teams.csv et wc_2026_fixtures.csv

In [82]:
teams = pd.read_csv("../data/raw/wc_2026_teams.csv")
teams.shape

(48, 7)

In [21]:
teams.head()

,team,group,confederation,fifa_rank,coach,best_wc_result,debut_2026
0,Mexico,A,CONCACAF,15,Javier Aguirre,"Quarter-finals (1970,1986)",No
1,South Africa,A,CAF,60,Hugo Broos,"Group stage (1998,2002,2010)",No
2,South Korea,A,AFC,25,Hong Myung-bo,Semi-finals (2002),No
3,Czechia,A,UEFA,41,Ivan Hasek,"Runner-up (1934,1962)",No
4,Canada,B,CONCACAF,30,Jesse Marsch,"Group stage (1986,2022)",No

In [22]:
fixtures = pd.read_csv("../data/raw/wc_2026_fixtures.csv")
fixtures.shape

(104, 15)

In [23]:
fixtures.head()

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek
2,A,Group Stage,South Korea,Mexico,Estadio Akron,Guadalajara,Mexico,2026-06-18,21:00 ET,AFC,25.0,Hong Myung-bo,CONCACAF,15.0,Javier Aguirre
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos
4,A,Group Stage,Czechia,Mexico,Estadio Azteca,Mexico City,Mexico,2026-06-24,21:00 ET,UEFA,41.0,Ivan Hasek,CONCACAF,15.0,Javier Aguirre

In [24]:
fixtures['stage'].unique()

<ArrowStringArray>
[    'Group Stage',     'Round of 32',     'Round of 16',   'Quarter-final',
      'Semi-final', '3rd Place Match',           'Final']
Length: 7, dtype: str

In [25]:
fixtures[fixtures['stage'] == 'Round of 32']

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
72,NaN,Round of 32,1A,2B,MetLife Stadium,East Rutherford,USA,2026-06-28,TBD,NaN,NaN,NaN,NaN,NaN,NaN
73,NaN,Round of 32,1B,2A,AT&T Stadium,Arlington,USA,2026-06-28,TBD,NaN,NaN,NaN,NaN,NaN,NaN
74,NaN,Round of 32,1C,2D,NRG Stadium,Houston,USA,2026-06-29,TBD,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,Round of 32,1D,2C,Rose Bowl,Pasadena,USA,2026-06-29,TBD,NaN,NaN,NaN,NaN,NaN,NaN
76,NaN,Round of 32,1E,2F,SoFi Stadium,Inglewood,USA,2026-06-30,TBD,NaN,NaN,NaN,NaN,NaN,NaN
77,NaN,Round of 32,1F,2E,Lumen Field,Seattle,USA,2026-06-30,TBD,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,Round of 32,1G,2H,Mercedes-Benz Stadium,Atlanta,USA,2026-07-01,TBD,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,Round of 32,1H,2G,Hard Rock Stadium,Miami,USA,2026-07-01,TBD,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,Round of 32,1I,2J,Lincoln Financial Field,Philadelphia,USA,2026-07-02,TBD,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,Round of 32,1J,2I,Arrowhead Stadium,Kansas City,USA,2026-07-02,TBD,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,Round of 32,1K,2L,Gillette Stadium,Foxborough,USA,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN
83,NaN,Round of 32,1L,2K,BC Place,Vancouver,Canada,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,Round of 32,Best 3rd #1,Best 3rd #2,BMO Field,Toronto,Canada,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN
85,NaN,Round of 32,Best 3rd #3,Best 3rd #4,Estadio BBVA,Monterrey,Mexico,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN
86,NaN,Round of 32,Best 3rd #5,Best 3rd #6,Estadio Akron,Guadalajara,Mexico,2026-07-04,TBD,NaN,NaN,NaN,NaN,NaN,NaN
87,NaN,Round of 32,Best 3rd #7,Best 3rd #8,Estadio Azteca,Mexico City,Mexico,2026-07-04,TBD,NaN,NaN,NaN,NaN,NaN,NaN

## 4. Harmonisation des noms d'équipes

In [26]:
teams_ref = set(teams['team'])
teams_elo = set(elo_latest['country'])

teams_ref - teams_elo

{'Türkiye', 'USA'}

In [27]:
teams_elo - teams_ref

{'Turkey', 'United States'}

In [28]:
teams_results = set(results['home_team']) | set(results['away_team'])

teams_ref - teams_results

{'Czechia', 'Türkiye', 'USA'}

In [29]:
for name in ['Czech Republic', 'United States', 'Turkey']:
    print(name, name in teams_results)

Czech Republic True
United States True
Turkey True

In [30]:
teams_fixtures = set(fixtures['team1']) | set(fixtures['team2'])

teams_ref - teams_fixtures

set()

In [31]:
name_mapping = {
    "United States": "USA",
    "Turkey": "Türkiye",
    "Czech Republic": "Czechia",
}

In [32]:
elo_latest['country'] = elo_latest['country'].replace(name_mapping)
set(teams_ref) - set(elo_latest['country'])

set()

In [33]:
results['home_team'] = results['home_team'].replace(name_mapping)
results['away_team'] = results['away_team'].replace(name_mapping)

teams_ref - (set(results['home_team']) | set(results['away_team']))

set()

In [34]:
elo['country'].nunique()

48

In [35]:
results['date'] = pd.to_datetime(results['date'])
results['year'] = results['date'].dt.year

In [36]:
mask = (
    results['home_team'].isin(teams_ref) &
    results['away_team'].isin(teams_ref) &
    (results['year'] >= 1901) &
    results['home_score'].notna()
)
matches = results[mask].copy()
matches.shape

(7571, 10)

In [37]:
matches['join_year'] = matches['year'] - 1

In [38]:
elo_simple = elo[['country', 'year', 'rating']]

matches = matches.merge(
    elo_simple.rename(columns={'country': 'home_team', 'year': 'join_year', 'rating': 'home_elo'}),
    on=['home_team', 'join_year'],
    how='left'
)

In [39]:
matches[['home_team', 'year', 'home_elo']].head()

   home_team  year  home_elo
0    England  1901       NaN
1    England  1902    2013.0
2    Uruguay  1902       NaN
3    England  1903    1995.0
4  Argentina  1903    2021.0

In [40]:
matches = matches.merge(
    elo_simple.rename(columns={'country': 'away_team', 'year': 'join_year', 'rating': 'away_elo'}),
    on=['away_team', 'join_year'],
    how='left'
)

In [41]:
matches[['home_elo', 'away_elo']].isna().sum()

home_elo    378
away_elo    325
dtype: int64

In [42]:
mask_complete = matches['home_elo'].notna() & matches['away_elo'].notna()
matches[~mask_complete].shape[0]

686

In [43]:
matches_clean = matches[mask_complete].copy()
matches_clean.shape

(6885, 13)

In [44]:
matches_clean.to_csv("../data/processed/matches_with_elo.csv", index=False)

In [45]:
matches_clean['elo_diff'] = matches_clean['home_elo'] - matches_clean['away_elo']
matches_clean[['home_team', 'away_team', 'elo_diff']].head()

   home_team away_team  elo_diff
1    England  Scotland      40.0
3    England  Scotland      12.0
4  Argentina   Uruguay     142.0
5   Scotland   England     -12.0
8    England  Scotland      83.0

In [46]:
import numpy as np

matches_clean['result'] = np.where(
    matches_clean['home_score'] > matches_clean['away_score'], 'home_win',
    np.where(matches_clean['home_score'] < matches_clean['away_score'], 'away_win', 'draw')
)

matches_clean['result'].value_counts()

result
home_win    3185
away_win    1926
draw        1774
Name: count, dtype: int64

In [47]:
neutral_matches = matches_clean[(matches_clean['neutral'] == True) & (matches_clean['elo_diff'] > 0)].copy()

bins = [0, 100, 200, 400, 1000]
labels = ['0-100', '100-200', '200-400', '400+']
neutral_matches['elo_diff_bucket'] = pd.cut(neutral_matches['elo_diff'], bins=bins, labels=labels)

neutral_matches.groupby('elo_diff_bucket')['result'].apply(lambda x: (x == 'home_win').mean())

elo_diff_bucket
0-100      0.443005
100-200    0.526984
200-400    0.642405
400+       0.800000
Name: result, dtype: float64

In [48]:
matches_clean['year'].quantile([0.8])

0.8    2013.0
Name: year, dtype: float64

In [49]:
train = matches_clean[matches_clean['year'] < 2014].copy()
test = matches_clean[matches_clean['year'] >= 2014].copy()

train.shape, test.shape

((5518, 15), (1367, 15))

In [50]:
from xgboost import XGBRegressor

features = ['elo_diff', 'neutral']

X_train = train[features]
y_train_home = train['home_score']

X_test = test[features]
y_test_home = test['home_score']

model_home = XGBRegressor(n_estimators=100, random_state=42)
model_home.fit(X_train, y_train_home)

preds_home = model_home.predict(X_test)
preds_home[:10]

array([1.1078972 , 0.9443795 , 0.56086314, 0.92487234, 1.6781956 ,
       1.5061138 , 1.9004884 , 3.0166252 , 1.3876376 , 2.9907036 ],
      dtype=float32)

In [51]:
from sklearn.metrics import mean_absolute_error

mae_model = mean_absolute_error(y_test_home, preds_home)
mae_model

1.050344774757063

In [52]:
baseline_pred = [y_train_home.mean()] * len(y_test_home)
mae_baseline = mean_absolute_error(y_test_home, baseline_pred)
mae_baseline

1.082429306972486

In [53]:
features = ['elo_diff', 'neutral']

X_train = train[features]
y_train_away = train['away_score']

X_test = test[features]
y_test_away = test['away_score']

model_away = XGBRegressor(n_estimators=100, random_state=42)
model_away.fit(X_train, y_train_away)

preds_away = model_away.predict(X_test)
preds_away[:10]

array([0.61760646, 0.84582424, 1.3375072 , 1.0990905 , 1.439769  ,
       0.9998916 , 0.58116   , 0.59627527, 1.1490264 , 0.72874016],
      dtype=float32)

In [54]:
from sklearn.metrics import mean_absolute_error

mae_model = mean_absolute_error(y_test_away, preds_away)
mae_model

0.8889737539947163

In [55]:
baseline_pred = [y_train_away.mean()] * len(y_test_away)
mae_baseline = mean_absolute_error(y_test_away, baseline_pred)
mae_baseline

0.8949894115235819

In [56]:
np.random.poisson(preds_home[0], size=10)

array([1, 1, 1, 2, 1, 1, 2, 1, 0, 2], dtype=int32)

In [61]:
sim_home = np.random.poisson(preds_home[0])
sim_away = np.random.poisson(preds_away[0])

if sim_home > sim_away:
    print("victoire domicile")
elif sim_home < sim_away:
    print("victoire extérieur")
else:
    print("nul")

victoire domicile

In [62]:
counts = {"victoire domicile": 0, "nul": 0, "victoire extérieur": 0}

for i in range(1000):
    sim_home = np.random.poisson(preds_home[0])
    sim_away = np.random.poisson(preds_away[0])

    if sim_home > sim_away:
        counts["victoire domicile"] += 1
    elif sim_home < sim_away:
        counts["victoire extérieur"] += 1
    else:
        counts["nul"] += 1

counts

{'victoire domicile': 475, 'nul': 297, 'victoire extérieur': 228}

In [68]:
def simulate_match(elo_diff, neutral, n_sim=1000):
    X_new = pd.DataFrame({'elo_diff': [elo_diff], 'neutral': [neutral]})
    lambda_home = model_home.predict(X_new)[0]
    lambda_away = model_away.predict(X_new)[0]

    counts = {"victoire domicile": 0, "nul": 0, "victoire extérieur": 0}

    for i in range(n_sim):
        sim_home = np.random.poisson(lambda_home)
        sim_away = np.random.poisson(lambda_away)

        if sim_home > sim_away:
            counts["victoire domicile"] += 1
        elif sim_home < sim_away:
            counts["victoire extérieur"] += 1
        else:
            counts["nul"] += 1

    return counts

simulate_match(150, False)

{'victoire domicile': 641, 'nul': 202, 'victoire extérieur': 157}

In [73]:
def play_match(elo_diff, neutral):
    X_new = pd.DataFrame({'elo_diff': [elo_diff], 'neutral': [neutral]})
    lambda_home = model_home.predict(X_new)[0]
    lambda_away = model_away.predict(X_new)[0]

    sim_home = np.random.poisson(lambda_home)
    sim_away = np.random.poisson(lambda_away)

    return sim_home, sim_away
play_match(150, False)

(2, 3)

In [74]:
from itertools import combinations

teams = ['A', 'B', 'C', 'D']
list(combinations(teams, 2))

[('A', 'B'), ('A', 'C'), ('A', 'D'), ('B', 'C'), ('B', 'D'), ('C', 'D')]

In [76]:
for home, away in combinations(teams, 2):
    score_home, score_away = play_match(0, True)

    standings[home]['gf'] += score_home
    standings[home]['ga'] += score_away
    standings[away]['gf'] += score_away
    standings[away]['ga'] += score_home

    if score_home > score_away:
        standings[home]['points'] += 3
    elif score_home < score_away:
        standings[away]['points'] += 3
    else:
        standings[home]['points'] += 1
        standings[away]['points'] += 1

standings

{'A': {'points': 6, 'gf': 2, 'ga': 2},
 'B': {'points': 4, 'gf': 4, 'ga': 4},
 'C': {'points': 4, 'gf': 3, 'ga': 2},
 'D': {'points': 2, 'gf': 1, 'ga': 2}}

In [77]:
ranking = sorted(standings.items(), key=lambda x: (x[1]['points'], x[1]['gf'] - x[1]['ga']), reverse=True)
ranking

[('A', {'points': 6, 'gf': 2, 'ga': 2}),
 ('C', {'points': 4, 'gf': 3, 'ga': 2}),
 ('B', {'points': 4, 'gf': 4, 'ga': 4}),
 ('D', {'points': 2, 'gf': 1, 'ga': 2})]

In [78]:
elo_latest.head()

,year,snapshot_date,country,rank,country_code,rating,rank_max,rating_max,rank_avg,rating_avg,rank_min,rating_min,matches_total,matches_home,matches_away,matches_neutral,wins,losses,draws,goals_for,goals_against,confederation,is_host
4587,2026,2026-12-31,Spain,1,ES,2165,1,2189,7,1946,19,1805,780,340,302,138,461,138,181,1591,697,UEFA,0
4588,2026,2026-12-31,Argentina,2,AR,2113,1,2172,5,1987,26,1751,1109,381,419,309,610,228,271,2112,1136,CONMEBOL,0
4589,2026,2026-12-31,France,3,FR,2081,1,2135,16,1795,40,1514,938,473,341,124,474,269,195,1706,1272,UEFA,0
4590,2026,2026-12-31,England,4,EN,2020,1,2213,4,1983,17,1810,1160,509,524,127,683,215,262,2719,1118,UEFA,0
4591,2026,2026-12-31,Brazil,5,BR,1984,1,2195,4,1998,20,1805,1065,372,346,347,670,172,223,2294,954,CONMEBOL,0

In [79]:
elo_lookup = elo_latest.set_index('country')['rating']

In [80]:
team1, team2, country = 'Czechia', 'Mexico', 'Mexico'

if team1 == country:
    host, other, neutral = team1, team2, False
elif team2 == country:
    host, other, neutral = team2, team1, False
else:
    host, other, neutral = team1, team2, True

host, other, neutral

('Mexico', 'Czechia', False)

In [84]:
group_a = fixtures[fixtures['group'] == 'A']
group_a_teams = teams[teams['group'] == 'A']['team']

standings = {team: {'points': 0, 'gf': 0, 'ga': 0} for team in group_a_teams}

for _, row in group_a.iterrows():
    team1, team2, country = row['team1'], row['team2'], row['country']

    if team1 == country:
        host, other, neutral = team1, team2, False
    elif team2 == country:
        host, other, neutral = team2, team1, False
    else:
        host, other, neutral = team1, team2, True

    elo_diff = elo_lookup[host] - elo_lookup[other]
    score_host, score_other = play_match(elo_diff, neutral)

    standings[host]['gf'] += score_host
    standings[host]['ga'] += score_other
    standings[other]['gf'] += score_other
    standings[other]['ga'] += score_host

    if score_host > score_other:
        standings[host]['points'] += 3
    elif score_host < score_other:
        standings[other]['points'] += 3
    else:
        standings[host]['points'] += 1
        standings[other]['points'] += 1

ranking = sorted(standings.items(), key=lambda x: (x[1]['points'], x[1]['gf'] - x[1]['ga']), reverse=True)
ranking

[('Mexico', {'points': 9, 'gf': 11, 'ga': 1}),
 ('South Africa', {'points': 4, 'gf': 4, 'ga': 4}),
 ('Czechia', {'points': 4, 'gf': 3, 'ga': 5}),
 ('South Korea', {'points': 0, 'gf': 1, 'ga': 9})]

In [85]:
n_sim = 1000
rank_counts = {team: {1: 0, 2: 0, 3: 0, 4: 0} for team in group_a_teams}

for sim in range(n_sim):
    standings = {team: {'points': 0, 'gf': 0, 'ga': 0} for team in group_a_teams}

    for _, row in group_a.iterrows():
        team1, team2, country = row['team1'], row['team2'], row['country']

        if team1 == country:
            host, other, neutral = team1, team2, False
        elif team2 == country:
            host, other, neutral = team2, team1, False
        else:
            host, other, neutral = team1, team2, True

        elo_diff = elo_lookup[host] - elo_lookup[other]
        score_host, score_other = play_match(elo_diff, neutral)

        standings[host]['gf'] += score_host
        standings[host]['ga'] += score_other
        standings[other]['gf'] += score_other
        standings[other]['ga'] += score_host

        if score_host > score_other:
            standings[host]['points'] += 3
        elif score_host < score_other:
            standings[other]['points'] += 3
        else:
            standings[host]['points'] += 1
            standings[other]['points'] += 1

    ranking = sorted(standings.items(), key=lambda x: (x[1]['points'], x[1]['gf'] - x[1]['ga']), reverse=True)

    for position, (team, stats) in enumerate(ranking, start=1):
        rank_counts[team][position] += 1

rank_counts

{'Mexico': {1: 766, 2: 171, 3: 53, 4: 10},
 'South Africa': {1: 18, 2: 80, 3: 236, 4: 666},
 'South Korea': {1: 111, 2: 388, 3: 317, 4: 184},
 'Czechia': {1: 105, 2: 361, 3: 394, 4: 140}}

In [88]:
def simulate_group(group_letter, n_sim=1000):
    group_teams = teams[teams['group'] == group_letter]['team'].tolist()
    group_fixtures = fixtures[fixtures['group'] == group_letter]

    rank_counts = {team: {1: 0, 2: 0, 3: 0, 4: 0} for team in group_teams}

    for sim in range(n_sim):
        standings = {team: {'points': 0, 'gf': 0, 'ga': 0} for team in group_teams}

        for _, row in group_fixtures.iterrows():
            team1, team2, country = row['team1'], row['team2'], row['country']

            if team1 == country:
                host, other, neutral = team1, team2, False
            elif team2 == country:
                host, other, neutral = team2, team1, False
            else:
                host, other, neutral = team1, team2, True

            elo_diff = elo_lookup[host] - elo_lookup[other]
            score_host, score_other = play_match(elo_diff, neutral)

            standings[host]['gf'] += score_host
            standings[host]['ga'] += score_other
            standings[other]['gf'] += score_other
            standings[other]['ga'] += score_host

            if score_host > score_other:
                standings[host]['points'] += 3
            elif score_host < score_other:
                standings[other]['points'] += 3
            else:
                standings[host]['points'] += 1
                standings[other]['points'] += 1

        ranking = sorted(standings.items(), key=lambda x: (x[1]['points'], x[1]['gf'] - x[1]['ga']), reverse=True)

        for position, (team, stats) in enumerate(ranking, start=1):
            rank_counts[team][position] += 1

    return rank_counts


all_results = {}
for group_letter in sorted(teams['group'].unique()):
    all_results[group_letter] = simulate_group(group_letter)

all_results

{'A': {'Mexico': {1: 766, 2: 171, 3: 52, 4: 11},
  'South Africa': {1: 10, 2: 87, 3: 215, 4: 688},
  'South Korea': {1: 106, 2: 400, 3: 338, 4: 156},
  'Czechia': {1: 118, 2: 342, 3: 395, 4: 145}},
 'B': {'Canada': {1: 531, 2: 375, 3: 88, 4: 6},
  'Switzerland': {1: 432, 2: 470, 3: 85, 4: 13},
  'Qatar': {1: 2, 2: 26, 3: 222, 4: 750},
  'Bosnia and Herzegovina': {1: 35, 2: 129, 3: 605, 4: 231}},
 'C': {'Brazil': {1: 566, 2: 271, 3: 116, 4: 47},
  'Morocco': {1: 335, 2: 408, 3: 195, 4: 62},
  'Haiti': {1: 60, 2: 213, 3: 401, 4: 326},
  'Scotland': {1: 39, 2: 108, 3: 288, 4: 565}},
 'D': {'USA': {1: 325, 2: 273, 3: 230, 4: 172},
  'Paraguay': {1: 170, 2: 224, 3: 242, 4: 364},
  'Australia': {1: 179, 2: 225, 3: 299, 4: 297},
  'Türkiye': {1: 326, 2: 278, 3: 229, 4: 167}},
 'E': {'Germany': {1: 491, 2: 311, 3: 186, 4: 12},
  'Curaçao': {1: 4, 2: 26, 3: 110, 4: 860},
  'Ivory Coast': {1: 156, 2: 283, 3: 459, 4: 102},
  'Ecuador': {1: 349, 2: 380, 3: 245, 4: 26}},
 'F': {'Netherlands': {1: 370, 2: 349, 3: 206, 4: 75},
  'Japan': {1: 487, 2: 323, 3: 138, 4: 52},
  'Sweden': {1: 102, 2: 211, 3: 364, 4: 323},
  'Tunisia': {1: 41, 2: 117, 3: 292, 4: 550}},
 'G': {'Belgium': {1: 624, 2: 231, 3: 105, 4: 40},
  'Egypt': {1: 139, 2: 267, 3: 323, 4: 271},
  'Iran': {1: 191, 2: 337, 3: 296, 4: 176},
  'New Zealand': {1: 46, 2: 165, 3: 276, 4: 513}},
 'H': {'Spain': {1: 924, 2: 70, 3: 6, 4: 0},
  'Cape Verde': {1: 2, 2: 191, 3: 315, 4: 492},
  'Saudi Arabia': {1: 31, 2: 266, 3: 376, 4: 327},
  'Uruguay': {1: 43, 2: 473, 3: 303, 4: 181}},
 'I': {'France': {1: 640, 2: 255, 3: 87, 4: 18},
  'Senegal': {1: 161, 2: 391, 3: 316, 4: 132},
  'Norway': {1: 188, 2: 276, 3: 372, 4: 164},
  'Iraq': {1: 11, 2: 78, 3: 225, 4: 686}},
 'J': {'Argentina': {1: 767, 2: 178, 3: 39, 4: 16},
  'Algeria': {1: 79, 2: 324, 3: 333, 4: 264},
  'Austria': {1: 120, 2: 358, 3: 327, 4: 195},
  'Jordan': {1: 34, 2: 140, 3: 301, 4: 525}},
 'K': {'Portugal': {1: 635, 2: 226, 3: 101, 4: 38},
  'DR Congo': {1: 57, 2: 210, 3: 338, 4: 395},
  'Uzbekistan': {1: 91, 2: 208, 3: 310, 4: 391},
  'Colombia': {1: 217, 2: 356, 3: 251, 4: 176}},
 'L': {'England': {1: 478, 2: 422, 3: 83, 4: 17},
  'Croatia': {1: 478, 2: 382, 3: 106, 4: 34},
  'Ghana': {1: 33, 2: 126, 3: 510, 4: 331},
  'Panama': {1: 11, 2: 70, 3: 301, 4: 618}}}

In [90]:
def simulate_group(group_letter, n_sim=1000):
    group_teams = teams[teams['group'] == group_letter]['team'].tolist()
    group_fixtures = fixtures[fixtures['group'] == group_letter]

    # Calcul des lambda UNE SEULE FOIS par match (pas par simulation)
    match_params = []
    for _, row in group_fixtures.iterrows():
        team1, team2, country = row['team1'], row['team2'], row['country']

        if team1 == country:
            host, other, neutral = team1, team2, False
        elif team2 == country:
            host, other, neutral = team2, team1, False
        else:
            host, other, neutral = team1, team2, True

        elo_diff = elo_lookup[host] - elo_lookup[other]
        X_new = pd.DataFrame({'elo_diff': [elo_diff], 'neutral': [neutral]})
        lambda_host = model_home.predict(X_new)[0]
        lambda_other = model_away.predict(X_new)[0]

        match_params.append((host, other, lambda_host, lambda_other))

    rank_counts = {team: {1: 0, 2: 0, 3: 0, 4: 0} for team in group_teams}

    for sim in range(n_sim):
        standings = {team: {'points': 0, 'gf': 0, 'ga': 0} for team in group_teams}

        for host, other, lambda_host, lambda_other in match_params:
            score_host = np.random.poisson(lambda_host)
            score_other = np.random.poisson(lambda_other)

            standings[host]['gf'] += score_host
            standings[host]['ga'] += score_other
            standings[other]['gf'] += score_other
            standings[other]['ga'] += score_host

            if score_host > score_other:
                standings[host]['points'] += 3
            elif score_host < score_other:
                standings[other]['points'] += 3
            else:
                standings[host]['points'] += 1
                standings[other]['points'] += 1

        ranking = sorted(standings.items(), key=lambda x: (x[1]['points'], x[1]['gf'] - x[1]['ga']), reverse=True)

        for position, (team, stats) in enumerate(ranking, start=1):
            rank_counts[team][position] += 1

    return rank_counts

In [91]:
all_results = {}
for group_letter in sorted(teams['group'].unique()):
    all_results[group_letter] = simulate_group(group_letter)

all_results

{'A': {'Mexico': {1: 792, 2: 154, 3: 41, 4: 13},
  'South Africa': {1: 12, 2: 88, 3: 236, 4: 664},
  'South Korea': {1: 84, 2: 371, 3: 353, 4: 192},
  'Czechia': {1: 112, 2: 387, 3: 370, 4: 131}},
 'B': {'Canada': {1: 514, 2: 391, 3: 88, 4: 7},
  'Switzerland': {1: 452, 2: 456, 3: 81, 4: 11},
  'Qatar': {1: 1, 2: 25, 3: 223, 4: 751},
  'Bosnia and Herzegovina': {1: 33, 2: 128, 3: 608, 4: 231}},
 'C': {'Brazil': {1: 534, 2: 311, 3: 110, 4: 45},
  'Morocco': {1: 351, 2: 391, 3: 199, 4: 59},
  'Haiti': {1: 68, 2: 201, 3: 430, 4: 301},
  'Scotland': {1: 47, 2: 97, 3: 261, 4: 595}},
 'D': {'USA': {1: 324, 2: 286, 3: 214, 4: 176},
  'Paraguay': {1: 190, 2: 230, 3: 258, 4: 322},
  'Australia': {1: 165, 2: 216, 3: 286, 4: 333},
  'Türkiye': {1: 321, 2: 268, 3: 242, 4: 169}},
 'E': {'Germany': {1: 462, 2: 329, 3: 184, 4: 25},
  'Curaçao': {1: 1, 2: 22, 3: 140, 4: 837},
  'Ivory Coast': {1: 175, 2: 254, 3: 457, 4: 114},
  'Ecuador': {1: 362, 2: 395, 3: 219, 4: 24}},
 'F': {'Netherlands': {1: 334, 2: 384, 3: 200, 4: 82},
  'Japan': {1: 527, 2: 286, 3: 147, 4: 40},
  'Sweden': {1: 111, 2: 205, 3: 365, 4: 319},
  'Tunisia': {1: 28, 2: 125, 3: 288, 4: 559}},
 'G': {'Belgium': {1: 609, 2: 234, 3: 117, 4: 40},
  'Egypt': {1: 131, 2: 289, 3: 318, 4: 262},
  'Iran': {1: 205, 2: 304, 3: 294, 4: 197},
  'New Zealand': {1: 55, 2: 173, 3: 271, 4: 501}},
 'H': {'Spain': {1: 913, 2: 76, 3: 9, 4: 2},
  'Cape Verde': {1: 10, 2: 173, 3: 358, 4: 459},
  'Saudi Arabia': {1: 24, 2: 260, 3: 358, 4: 358},
  'Uruguay': {1: 53, 2: 491, 3: 275, 4: 181}},
 'I': {'France': {1: 649, 2: 242, 3: 90, 4: 19},
  'Senegal': {1: 149, 2: 351, 3: 348, 4: 152},
  'Norway': {1: 183, 2: 307, 3: 356, 4: 154},
  'Iraq': {1: 19, 2: 100, 3: 206, 4: 675}},
 'J': {'Argentina': {1: 774, 2: 165, 3: 49, 4: 12},
  'Algeria': {1: 87, 2: 309, 3: 330, 4: 274},
  'Austria': {1: 111, 2: 352, 3: 326, 4: 211},
  'Jordan': {1: 28, 2: 174, 3: 295, 4: 503}},
 'K': {'Portugal': {1: 628, 2: 242, 3: 93, 4: 37},
  'DR Congo': {1: 78, 2: 200, 3: 341, 4: 381},
  'Uzbekistan': {1: 69, 2: 204, 3: 330, 4: 397},
  'Colombia': {1: 225, 2: 354, 3: 236, 4: 185}},
 'L': {'England': {1: 533, 2: 362, 3: 94, 4: 11},
  'Croatia': {1: 410, 2: 421, 3: 128, 4: 41},
  'Ghana': {1: 31, 2: 143, 3: 484, 4: 342},
  'Panama': {1: 26, 2: 74, 3: 294, 4: 606}}}

In [96]:
def play_group(group_letter):
    group_teams = teams[teams['group'] == group_letter]['team'].tolist()
    group_fixtures = fixtures[fixtures['group'] == group_letter]

    standings = {team: {'points': 0, 'gf': 0, 'ga': 0} for team in group_teams}

    for _, row in group_fixtures.iterrows():
        team1, team2, country = row['team1'], row['team2'], row['country']

        if team1 == country:
            host, other, neutral = team1, team2, False
        elif team2 == country:
            host, other, neutral = team2, team1, False
        else:
            host, other, neutral = team1, team2, True

        elo_diff = elo_lookup[host] - elo_lookup[other]
        X_new = pd.DataFrame({'elo_diff': [elo_diff], 'neutral': [neutral]})
        lambda_host = model_home.predict(X_new)[0]
        lambda_other = model_away.predict(X_new)[0]

        score_host = np.random.poisson(lambda_host)
        score_other = np.random.poisson(lambda_other)

        standings[host]['gf'] += score_host
        standings[host]['ga'] += score_other
        standings[other]['gf'] += score_other
        standings[other]['ga'] += score_host

        if score_host > score_other:
            standings[host]['points'] += 3
        elif score_host < score_other:
            standings[other]['points'] += 3
        else:
            standings[host]['points'] += 1
            standings[other]['points'] += 1

    ranking = sorted(standings.items(), key=lambda x: (x[1]['points'], x[1]['gf'] - x[1]['ga']), reverse=True)

    return ranking

In [97]:
play_group('A')

[('Czechia', {'points': 9, 'gf': 7, 'ga': 2}),
 ('Mexico', {'points': 6, 'gf': 7, 'ga': 2}),
 ('South Africa', {'points': 1, 'gf': 2, 'ga': 6}),
 ('South Korea', {'points': 1, 'gf': 4, 'ga': 10})]

In [98]:
third_place_table = pd.read_csv('../data/raw/wc2026_third_place_allocation.csv')

def get_third_place_allocation(qualified_groups):
    groups_str = ''.join(sorted(qualified_groups))
    row = third_place_table[third_place_table['groups'] == groups_str].iloc[0]
    return row[['1A', '1B', '1D', '1E', '1G', '1I', '1K', '1L']].to_dict()

In [99]:
get_third_place_allocation(['B', 'D', 'E', 'F', 'I', 'J', 'K', 'L'])

{'1A': '3E',
 '1B': '3J',
 '1D': '3B',
 '1E': '3D',
 '1G': '3I',
 '1I': '3F',
 '1K': '3L',
 '1L': '3K'}

In [100]:
group_letters = sorted(teams['group'].unique())

group_rankings = {}
third_placed = []

for group_letter in group_letters:
    ranking = play_group(group_letter)
    group_rankings[group_letter] = ranking

    third_team, third_stats = ranking[2]
    third_placed.append((group_letter, third_team, third_stats))

third_placed_sorted = sorted(
    third_placed,
    key=lambda x: (x[2]['points'], x[2]['gf'] - x[2]['ga'], x[2]['gf']),
    reverse=True
)

qualified_groups = [g for g, team, stats in third_placed_sorted[:8]]

allocation = get_third_place_allocation(qualified_groups)

qualified_groups, allocation

(['E', 'C', 'F', 'G', 'A', 'L', 'J', 'K'],
 {'1A': '3E',
  '1B': '3G',
  '1D': '3J',
  '1E': '3C',
  '1G': '3A',
  '1I': '3F',
  '1K': '3L',
  '1L': '3K'})

In [101]:
placeholder_map = {}

for group_letter, ranking in group_rankings.items():
    first_team = ranking[0][0]
    second_team = ranking[1][0]
    placeholder_map[f'1{group_letter}'] = first_team
    placeholder_map[f'2{group_letter}'] = second_team

for position, (group_letter, team, stats) in enumerate(third_placed_sorted[:8], start=1):
    placeholder_map[f'Best 3rd #{position}'] = team

r32 = fixtures[fixtures['stage'] == 'Round of 32'].copy()
r32['team1_real'] = r32['team1'].map(placeholder_map)
r32['team2_real'] = r32['team2'].map(placeholder_map)

r32[['team1', 'team1_real', 'team2', 'team2_real']]

          team1   team1_real        team2   team2_real
72           1A       Mexico           2B  Switzerland
73           1B       Canada           2A  South Korea
74           1C       Brazil           2D          USA
75           1D    Australia           2C        Haiti
76           1E      Germany           2F        Japan
77           1F  Netherlands           2E      Ecuador
78           1G         Iran           2H      Uruguay
79           1H        Spain           2G      Belgium
80           1I       France           2J      Algeria
81           1J    Argentina           2I       Norway
82           1K     Portugal           2L      England
83           1L      Croatia           2K     Colombia
84  Best 3rd #1  Ivory Coast  Best 3rd #2      Morocco
85  Best 3rd #3      Tunisia  Best 3rd #4        Egypt
86  Best 3rd #5      Czechia  Best 3rd #6        Ghana
87  Best 3rd #7       Jordan  Best 3rd #8   Uzbekistan

In [102]:
def play_knockout_match(team1, team2, country):
    if team1 == country:
        host, other, neutral = team1, team2, False
    elif team2 == country:
        host, other, neutral = team2, team1, False
    else:
        host, other, neutral = team1, team2, True

    elo_diff = elo_lookup[host] - elo_lookup[other]
    X_new = pd.DataFrame({'elo_diff': [elo_diff], 'neutral': [neutral]})
    lambda_host = model_home.predict(X_new)[0]
    lambda_other = model_away.predict(X_new)[0]

    score_host = np.random.poisson(lambda_host)
    score_other = np.random.poisson(lambda_other)

    if score_host > score_other:
        return host, other
    elif score_host < score_other:
        return other, host
    else:
        p_host_wins = 1 / (1 + 10 ** (-elo_diff / 400))
        if np.random.random() < p_host_wins:
            return host, other
        else:
            return other, host


def play_round(stage_name, label_prefix, prev_map):
    round_fixtures = fixtures[fixtures['stage'] == stage_name].copy()
    round_fixtures['team1_real'] = round_fixtures['team1'].map(prev_map)
    round_fixtures['team2_real'] = round_fixtures['team2'].map(prev_map)

    results = round_fixtures.apply(
        lambda row: play_knockout_match(row['team1_real'], row['team2_real'], row['country']),
        axis=1
    )
    round_fixtures['winner'] = [w for w, l in results]
    round_fixtures['loser'] = [l for w, l in results]

    winners_map = {f'{label_prefix}{i}': w for i, w in enumerate(round_fixtures['winner'], start=1)}

    return round_fixtures, winners_map


r32_results, r32_winners_map = play_round('Round of 32', 'R32 W', placeholder_map)
r16_results, qf_map = play_round('Round of 16', 'QF', r32_winners_map)
qf_results, sf_map = play_round('Quarter-final', 'SF', qf_map)
sf_results, _ = play_round('Semi-final', 'Finalist ', sf_map)

final_map = {f'Finalist {i}': w for i, w in enumerate(sf_results['winner'], start=1)}
final_fixture = fixtures[fixtures['stage'] == 'Final'].iloc[0]
team1_final = final_map[final_fixture['team1']]
team2_final = final_map[final_fixture['team2']]
champion, runner_up = play_knockout_match(team1_final, team2_final, final_fixture['country'])

third_place_fixture = fixtures[fixtures['stage'] == '3rd Place Match'].iloc[0]
loser1, loser2 = sf_results['loser'].tolist()
third_place, fourth_place = play_knockout_match(loser1, loser2, third_place_fixture['country'])

champion, runner_up, third_place, fourth_place

('Morocco', 'Spain', 'Argentina', 'Switzerland')

In [103]:
stage_order = ['Group Stage', 'Round of 32', 'Round of 16', 'Quarter-final', 'Semi-final', 'Final', 'Champion']

def simulate_tournament():
    stage_reached = {team: 'Group Stage' for team in teams['team']}

    group_rankings = {}
    third_placed = []

    for group_letter in group_letters:
        ranking = play_group(group_letter)
        group_rankings[group_letter] = ranking

        stage_reached[ranking[0][0]] = 'Round of 32'
        stage_reached[ranking[1][0]] = 'Round of 32'

        third_team, third_stats = ranking[2]
        third_placed.append((group_letter, third_team, third_stats))

    third_placed_sorted = sorted(
        third_placed,
        key=lambda x: (x[2]['points'], x[2]['gf'] - x[2]['ga'], x[2]['gf']),
        reverse=True
    )

    placeholder_map = {}
    for group_letter, ranking in group_rankings.items():
        placeholder_map[f'1{group_letter}'] = ranking[0][0]
        placeholder_map[f'2{group_letter}'] = ranking[1][0]

    for position, (group_letter, team, stats) in enumerate(third_placed_sorted[:8], start=1):
        placeholder_map[f'Best 3rd #{position}'] = team
        stage_reached[team] = 'Round of 32'

    r32_results, r32_winners_map = play_round('Round of 32', 'R32 W', placeholder_map)
    for team in pd.concat([r32_results['team1_real'], r32_results['team2_real']]):
        stage_reached[team] = 'Round of 32'

    r16_results, qf_map = play_round('Round of 16', 'QF', r32_winners_map)
    for team in pd.concat([r16_results['team1_real'], r16_results['team2_real']]):
        stage_reached[team] = 'Round of 16'

    qf_results, sf_map = play_round('Quarter-final', 'SF', qf_map)
    for team in pd.concat([qf_results['team1_real'], qf_results['team2_real']]):
        stage_reached[team] = 'Quarter-final'

    sf_results, _ = play_round('Semi-final', 'Finalist ', sf_map)
    for team in pd.concat([sf_results['team1_real'], sf_results['team2_real']]):
        stage_reached[team] = 'Semi-final'

    final_map = {f'Finalist {i}': w for i, w in enumerate(sf_results['winner'], start=1)}
    final_fixture = fixtures[fixtures['stage'] == 'Final'].iloc[0]
    team1_final = final_map[final_fixture['team1']]
    team2_final = final_map[final_fixture['team2']]
    stage_reached[team1_final] = 'Final'
    stage_reached[team2_final] = 'Final'

    champion, runner_up = play_knockout_match(team1_final, team2_final, final_fixture['country'])
    stage_reached[champion] = 'Champion'

    return stage_reached


n_sim = 100
reach_counts = {team: {stage: 0 for stage in stage_order} for team in teams['team']}

for sim in range(n_sim):
    result = simulate_tournament()
    for team, stage in result.items():
        reach_counts[team][stage] += 1

reach_counts

{'Mexico': {'Group Stage': 1,
  'Round of 32': 36,
  'Round of 16': 24,
  'Quarter-final': 22,
  'Semi-final': 12,
  'Final': 0,
  'Champion': 5},
 'South Africa': {'Group Stage': 72,
  'Round of 32': 20,
  'Round of 16': 7,
  'Quarter-final': 1,
  'Semi-final': 0,
  'Final': 0,
  'Champion': 0},
 'South Korea': {'Group Stage': 23,
  'Round of 32': 36,
  'Round of 16': 21,
  'Quarter-final': 10,
  'Semi-final': 6,
  'Final': 3,
  'Champion': 1},
 'Czechia': {'Group Stage': 36,
  'Round of 32': 33,
  'Round of 16': 19,
  'Quarter-final': 7,
  'Semi-final': 3,
  'Final': 2,
  'Champion': 0},
 'Canada': {'Group Stage': 0,
  'Round of 32': 51,
  'Round of 16': 28,
  'Quarter-final': 11,
  'Semi-final': 9,
  'Final': 1,
  'Champion': 0},
 'Switzerland': {'Group Stage': 4,
  'Round of 32': 50,
  'Round of 16': 19,
  'Quarter-final': 14,
  'Semi-final': 8,
  'Final': 4,
  'Champion': 1},
 'Qatar': {'Group Stage': 89,
  'Round of 32': 9,
  'Round of 16': 2,
  'Quarter-final': 0,
  'Semi-final': 0,
  'Final': 0,
  'Champion': 0},
 'Bosnia and Herzegovina': {'Group Stage': 45,
  'Round of 32': 41,
  'Round of 16': 10,
  'Quarter-final': 4,
  'Semi-final': 0,
  'Final': 0,
  'Champion': 0},
 'Brazil': {'Group Stage': 4,
  'Round of 32': 28,
  'Round of 16': 19,
  'Quarter-final': 14,
  'Semi-final': 14,
  'Final': 11,
  'Champion': 10},
 'Morocco': {'Group Stage': 10,
  'Round of 32': 29,
  'Round of 16': 38,
  'Quarter-final': 12,
  'Semi-final': 9,
  'Final': 2,
  'Champion': 0},
 'Haiti': {'Group Stage': 38,
  'Round of 32': 48,
  'Round of 16': 12,
  'Quarter-final': 2,
  'Semi-final': 0,
  'Final': 0,
  'Champion': 0},
 'Scotland': {'Group Stage': 75,
  'Round of 32': 13,
  'Round of 16': 7,
  'Quarter-final': 4,
  'Semi-final': 1,
  'Final': 0,
  'Champion': 0},
 'USA': {'Group Stage': 17,
  'Round of 32': 54,
  'Round of 16': 9,
  'Quarter-final': 13,
  'Semi-final': 5,
  'Final': 2,
  'Champion': 0},
 'Paraguay': {'Group Stage': 40,
  'Round of 32': 40,
  'Round of 16': 14,
  'Quarter-final': 0,
  'Semi-final': 2,
  'Final': 4,
  'Champion': 0},
 'Australia': {'Group Stage': 48,
  'Round of 32': 27,
  'Round of 16': 14,
  'Quarter-final': 7,
  'Semi-final': 3,
  'Final': 0,
  'Champion': 1},
 'Türkiye': {'Group Stage': 26,
  'Round of 32': 32,
  'Round of 16': 24,
  'Quarter-final': 10,
  'Semi-final': 6,
  'Final': 1,
  'Champion': 1},
 'Germany': {'Group Stage': 2,
  'Round of 32': 40,
  'Round of 16': 34,
  'Quarter-final': 15,
  'Semi-final': 6,
  'Final': 3,
  'Champion': 0},
 'Curaçao': {'Group Stage': 93,
  'Round of 32': 6,
  'Round of 16': 1,
  'Quarter-final': 0,
  'Semi-final': 0,
  'Final': 0,
  'Champion': 0},
 'Ivory Coast': {'Group Stage': 19,
  'Round of 32': 48,
  'Round of 16': 25,
  'Quarter-final': 7,
  'Semi-final': 0,
  'Final': 0,
  'Champion': 1},
 'Ecuador': {'Group Stage': 5,
  'Round of 32': 39,
  'Round of 16': 28,
  'Quarter-final': 11,
  'Semi-final': 5,
  'Final': 2,
  'Champion': 10},
 'Netherlands': {'Group Stage': 11,
  'Round of 32': 50,
  'Round of 16': 20,
  'Quarter-final': 17,
  'Semi-final': 1,
  'Final': 0,
  'Champion': 1},
 'Japan': {'Group Stage': 9,
  'Round of 32': 34,
  'Round of 16': 18,
  'Quarter-final': 31,
  'Semi-final': 7,
  'Final': 0,
  'Champion': 1},
 'Sweden': {'Group Stage': 47,
  'Round of 32': 31,
  'Round of 16': 9,
  'Quarter-final': 8,
  'Semi-final': 2,
  'Final': 3,
  'Champion': 0},
 'Tunisia': {'Group Stage': 63,
  'Round of 32': 30,
  'Round of 16': 6,
  'Quarter-final': 1,
  'Semi-final': 0,
  'Final': 0,
  'Champion': 0},
 'Belgium': {'Group Stage': 6,
  'Round of 32': 35,
  'Round of 16': 31,
  'Quarter-final': 14,
  'Semi-final': 8,
  'Final': 4,
  'Champion': 2},
 'Egypt': {'Group Stage': 34,
  'Round of 32': 50,
  'Round of 16': 11,
  'Quarter-final': 3,
  'Semi-final': 2,
  'Final': 0,
  'Champion': 0},
 'Iran': {'Group Stage': 34,
  'Round of 32': 46,
  'Round of 16': 15,
  'Quarter-final': 3,
  'Semi-final': 2,
  'Final': 0,
  'Champion': 0},
 'New Zealand': {'Group Stage': 62,
  'Round of 32': 26,
  'Round of 16': 10,
  'Quarter-final': 0,
  'Semi-final': 2,
  'Final': 0,
  'Champion': 0},
 'Spain': {'Group Stage': 0,
  'Round of 32': 8,
  'Round of 16': 23,
  'Quarter-final': 15,
  'Semi-final': 14,
  'Final': 10,
  'Champion': 30},
 'Cape Verde': {'Group Stage': 63,
  'Round of 32': 25,
  'Round of 16': 9,
  'Quarter-final': 2,
  'Semi-final': 1,
  'Final': 0,
  'Champion': 0},
 'Saudi Arabia': {'Group Stage': 51,
  'Round of 32': 34,
  'Round of 16': 10,
  'Quarter-final': 3,
  'Semi-final': 2,
  'Final': 0,
  'Champion': 0},
 'Uruguay': {'Group Stage': 36,
  'Round of 32': 29,
  'Round of 16': 26,
  'Quarter-final': 1,
  'Semi-final': 4,
  'Final': 3,
  'Champion': 1},
 'France': {'Group Stage': 1,
  'Round of 32': 28,
  'Round of 16': 41,
  'Quarter-final': 12,
  'Semi-final': 6,
  'Final': 5,
  'Champion': 7},
 'Senegal': {'Group Stage': 22,
  'Round of 32': 49,
  'Round of 16': 12,
  'Quarter-final': 10,
  'Semi-final': 6,
  'Final': 1,
  'Champion': 0},
 'Norway': {'Group Stage': 28,
  'Round of 32': 32,
  'Round of 16': 16,
  'Quarter-final': 10,
  'Semi-final': 9,
  'Final': 5,
  'Champion': 0},
 'Iraq': {'Group Stage': 76,
  'Round of 32': 18,
  'Round of 16': 4,
  'Quarter-final': 2,
  'Semi-final': 0,
  'Final': 0,
  'Champion': 0},
 'Argentina': {'Group Stage': 3,
  'Round of 32': 25,
  'Round of 16': 19,
  'Quarter-final': 22,
  'Semi-final': 8,
  'Final': 5,
  'Champion': 18},
 'Algeria': {'Group Stage': 43,
  'Round of 32': 33,
  'Round of 16': 13,
  'Quarter-final': 9,
  'Semi-final': 2,
  'Final': 0,
  'Champion': 0},
 'Austria': {'Group Stage': 31,
  'Round of 32': 42,
  'Round of 16': 22,
  'Quarter-final': 2,
  'Semi-final': 2,
  'Final': 1,
  'Champion': 0},
 'Jordan': {'Group Stage': 54,
  'Round of 32': 35,
  'Round of 16': 9,
  'Quarter-final': 1,
  'Semi-final': 1,
  'Final': 0,
  'Champion': 0},
 'Portugal': {'Group Stage': 5,
  'Round of 32': 39,
  'Round of 16': 25,
  'Quarter-final': 15,
  'Semi-final': 5,
  'Final': 10,
  'Champion': 1},
 'DR Congo': {'Group Stage': 47,
  'Round of 32': 37,
  'Round of 16': 12,
  'Quarter-final': 3,
  'Semi-final': 0,
  'Final': 1,
  'Champion': 0},
 'Uzbekistan': {'Group Stage': 56,
  'Round of 32': 28,
  'Round of 16': 10,
  'Quarter-final': 4,
  'Semi-final': 2,
  'Final': 0,
  'Champion': 0},
 'Colombia': {'Group Stage': 30,
  'Round of 32': 29,
  'Round of 16': 17,
  'Quarter-final': 7,
  'Semi-final': 9,
  'Final': 4,
  'Champion': 4},
 'England': {'Group Stage': 8,
  'Round of 32': 39,
  'Round of 16': 30,
  'Quarter-final': 13,
  'Semi-final': 4,
  'Final': 4,
  'Champion': 2},
 'Croatia': {'Group Stage': 12,
  'Round of 32': 32,
  'Round of 16': 16,
  'Quarter-final': 17,
  'Semi-final': 11,
  'Final': 9,
  'Champion': 3},
 'Ghana': {'Group Stage': 52,
  'Round of 32': 36,
  'Round of 16': 8,
  'Quarter-final': 4,
  'Semi-final': 0,
  'Final': 0,
  'Champion': 0},
 'Panama': {'Group Stage': 69,
  'Round of 32': 20,
  'Round of 16': 3,
  'Quarter-final': 7,
  'Semi-final': 1,
  'Final': 0,
  'Champion': 0}}

In [104]:
all_group_rows = []
for group_letter in group_letters:
    group_fixtures = fixtures[fixtures['group'] == group_letter]
    for _, row in group_fixtures.iterrows():
        team1, team2, country = row['team1'], row['team2'], row['country']
        if team1 == country:
            host, other, neutral = team1, team2, False
        elif team2 == country:
            host, other, neutral = team2, team1, False
        else:
            host, other, neutral = team1, team2, True
        elo_diff = elo_lookup[host] - elo_lookup[other]
        all_group_rows.append({'group': group_letter, 'host': host, 'other': other, 'elo_diff': elo_diff, 'neutral': neutral})

all_group_rows_df = pd.DataFrame(all_group_rows)
X_all = all_group_rows_df[['elo_diff', 'neutral']]
all_group_rows_df['lambda_host'] = model_home.predict(X_all)
all_group_rows_df['lambda_other'] = model_away.predict(X_all)

group_match_params = {}
for group_letter, group_df in all_group_rows_df.groupby('group'):
    group_match_params[group_letter] = list(
        group_df[['host', 'other', 'lambda_host', 'lambda_other']].itertuples(index=False, name=None)
    )


def play_group_fast(group_letter, group_match_params):
    group_teams = teams[teams['group'] == group_letter]['team'].tolist()
    standings = {team: {'points': 0, 'gf': 0, 'ga': 0} for team in group_teams}

    for host, other, lambda_host, lambda_other in group_match_params[group_letter]:
        score_host = np.random.poisson(lambda_host)
        score_other = np.random.poisson(lambda_other)

        standings[host]['gf'] += score_host
        standings[host]['ga'] += score_other
        standings[other]['gf'] += score_other
        standings[other]['ga'] += score_host

        if score_host > score_other:
            standings[host]['points'] += 3
        elif score_host < score_other:
            standings[other]['points'] += 3
        else:
            standings[host]['points'] += 1
            standings[other]['points'] += 1

    ranking = sorted(standings.items(), key=lambda x: (x[1]['points'], x[1]['gf'] - x[1]['ga']), reverse=True)
    return ranking


def play_round(stage_name, label_prefix, prev_map):
    round_fixtures = fixtures[fixtures['stage'] == stage_name].copy()
    round_fixtures['team1_real'] = round_fixtures['team1'].map(prev_map)
    round_fixtures['team2_real'] = round_fixtures['team2'].map(prev_map)

    hosts, others, neutrals = [], [], []
    for _, row in round_fixtures.iterrows():
        team1, team2, country = row['team1_real'], row['team2_real'], row['country']
        if team1 == country:
            host, other, neutral = team1, team2, False
        elif team2 == country:
            host, other, neutral = team2, team1, False
        else:
            host, other, neutral = team1, team2, True
        hosts.append(host)
        others.append(other)
        neutrals.append(neutral)

    elo_diffs = [elo_lookup[h] - elo_lookup[o] for h, o in zip(hosts, others)]
    X_round = pd.DataFrame({'elo_diff': elo_diffs, 'neutral': neutrals})
    lambda_hosts = model_home.predict(X_round)
    lambda_others = model_away.predict(X_round)

    winners, losers = [], []
    for host, other, lambda_host, lambda_other in zip(hosts, others, lambda_hosts, lambda_others):
        score_host = np.random.poisson(lambda_host)
        score_other = np.random.poisson(lambda_other)

        if score_host > score_other:
            winners.append(host); losers.append(other)
        elif score_host < score_other:
            winners.append(other); losers.append(host)
        else:
            elo_diff = elo_lookup[host] - elo_lookup[other]
            p_host_wins = 1 / (1 + 10 ** (-elo_diff / 400))
            if np.random.random() < p_host_wins:
                winners.append(host); losers.append(other)
            else:
                winners.append(other); losers.append(host)

    round_fixtures['winner'] = winners
    round_fixtures['loser'] = losers
    winners_map = {f'{label_prefix}{i}': w for i, w in enumerate(winners, start=1)}

    return round_fixtures, winners_map


def simulate_tournament():
    stage_reached = {team: 'Group Stage' for team in teams['team']}

    group_rankings = {}
    third_placed = []

    for group_letter in group_letters:
        ranking = play_group_fast(group_letter, group_match_params)
        group_rankings[group_letter] = ranking

        stage_reached[ranking[0][0]] = 'Round of 32'
        stage_reached[ranking[1][0]] = 'Round of 32'

        third_team, third_stats = ranking[2]
        third_placed.append((group_letter, third_team, third_stats))

    third_placed_sorted = sorted(
        third_placed,
        key=lambda x: (x[2]['points'], x[2]['gf'] - x[2]['ga'], x[2]['gf']),
        reverse=True
    )

    placeholder_map = {}
    for group_letter, ranking in group_rankings.items():
        placeholder_map[f'1{group_letter}'] = ranking[0][0]
        placeholder_map[f'2{group_letter}'] = ranking[1][0]

    for position, (group_letter, team, stats) in enumerate(third_placed_sorted[:8], start=1):
        placeholder_map[f'Best 3rd #{position}'] = team
        stage_reached[team] = 'Round of 32'

    r32_results, r32_winners_map = play_round('Round of 32', 'R32 W', placeholder_map)
    for team in pd.concat([r32_results['team1_real'], r32_results['team2_real']]):
        stage_reached[team] = 'Round of 32'

    r16_results, qf_map = play_round('Round of 16', 'QF', r32_winners_map)
    for team in pd.concat([r16_results['team1_real'], r16_results['team2_real']]):
        stage_reached[team] = 'Round of 16'

    qf_results, sf_map = play_round('Quarter-final', 'SF', qf_map)
    for team in pd.concat([qf_results['team1_real'], qf_results['team2_real']]):
        stage_reached[team] = 'Quarter-final'

    sf_results, _ = play_round('Semi-final', 'Finalist ', sf_map)
    for team in pd.concat([sf_results['team1_real'], sf_results['team2_real']]):
        stage_reached[team] = 'Semi-final'

    final_map = {f'Finalist {i}': w for i, w in enumerate(sf_results['winner'], start=1)}
    final_fixture = fixtures[fixtures['stage'] == 'Final'].iloc[0]
    team1_final = final_map[final_fixture['team1']]
    team2_final = final_map[final_fixture['team2']]
    stage_reached[team1_final] = 'Final'
    stage_reached[team2_final] = 'Final'

    champion, runner_up = play_knockout_match(team1_final, team2_final, final_fixture['country'])
    stage_reached[champion] = 'Champion'

    return stage_reached


n_sim = 1000
reach_counts = {team: {stage: 0 for stage in stage_order} for team in teams['team']}

for sim in range(n_sim):
    result = simulate_tournament()
    for team, stage in result.items():
        reach_counts[team][stage] += 1

reach_counts

{'Mexico': {'Group Stage': 11,
  'Round of 32': 354,
  'Round of 16': 249,
  'Quarter-final': 216,
  'Semi-final': 126,
  'Final': 21,
  'Champion': 23},
 'South Africa': {'Group Stage': 782,
  'Round of 32': 168,
  'Round of 16': 35,
  'Quarter-final': 13,
  'Semi-final': 2,
  'Final': 0,
  'Champion': 0},
 'South Korea': {'Group Stage': 258,
  'Round of 32': 429,
  'Round of 16': 186,
  'Quarter-final': 76,
  'Semi-final': 40,
  'Final': 9,
  'Champion': 2},
 'Czechia': {'Group Stage': 253,
  'Round of 32': 421,
  'Round of 16': 203,
  'Quarter-final': 77,
  'Semi-final': 37,
  'Final': 7,
  'Champion': 2},
 'Canada': {'Group Stage': 25,
  'Round of 32': 462,
  'Round of 16': 289,
  'Quarter-final': 131,
  'Semi-final': 84,
  'Final': 6,
  'Champion': 3},
 'Switzerland': {'Group Stage': 22,
  'Round of 32': 455,
  'Round of 16': 238,
  'Quarter-final': 138,
  'Semi-final': 112,
  'Final': 20,
  'Champion': 15},
 'Qatar': {'Group Stage': 913,
  'Round of 32': 70,
  'Round of 16': 13,
  'Quarter-final': 4,
  'Semi-final': 0,
  'Final': 0,
  'Champion': 0},
 'Bosnia and Herzegovina': {'Group Stage': 495,
  'Round of 32': 378,
  'Round of 16': 88,
  'Quarter-final': 32,
  'Semi-final': 7,
  'Final': 0,
  'Champion': 0},
 'Brazil': {'Group Stage': 88,
  'Round of 32': 311,
  'Round of 16': 180,
  'Quarter-final': 136,
  'Semi-final': 124,
  'Final': 97,
  'Champion': 64},
 'Morocco': {'Group Stage': 114,
  'Round of 32': 402,
  'Round of 16': 281,
  'Quarter-final': 98,
  'Semi-final': 78,
  'Final': 20,
  'Champion': 7},
 'Haiti': {'Group Stage': 428,
  'Round of 32': 467,
  'Round of 16': 79,
  'Quarter-final': 22,
  'Semi-final': 3,
  'Final': 1,
  'Champion': 0},
 'Scotland': {'Group Stage': 651,
  'Round of 32': 205,
  'Round of 16': 77,
  'Quarter-final': 38,
  'Semi-final': 24,
  'Final': 3,
  'Champion': 2},
 'USA': {'Group Stage': 208,
  'Round of 32': 469,
  'Round of 16': 183,
  'Quarter-final': 58,
  'Semi-final': 57,
  'Final': 20,
  'Champion': 5},
 'Paraguay': {'Group Stage': 393,
  'Round of 32': 281,
  'Round of 16': 192,
  'Quarter-final': 69,
  'Semi-final': 51,
  'Final': 8,
  'Champion': 6},
 'Australia': {'Group Stage': 400,
  'Round of 32': 291,
  'Round of 16': 163,
  'Quarter-final': 81,
  'Semi-final': 54,
  'Final': 8,
  'Champion': 3},
 'Türkiye': {'Group Stage': 230,
  'Round of 32': 344,
  'Round of 16': 191,
  'Quarter-final': 119,
  'Semi-final': 89,
  'Final': 16,
  'Champion': 11},
 'Germany': {'Group Stage': 42,
  'Round of 32': 388,
  'Round of 16': 237,
  'Quarter-final': 193,
  'Semi-final': 69,
  'Final': 40,
  'Champion': 31},
 'Curaçao': {'Group Stage': 926,
  'Round of 32': 61,
  'Round of 16': 11,
  'Quarter-final': 2,
  'Semi-final': 0,
  'Final': 0,
  'Champion': 0},
 'Ivory Coast': {'Group Stage': 230,
  'Round of 32': 521,
  'Round of 16': 164,
  'Quarter-final': 61,
  'Semi-final': 19,
  'Final': 4,
  'Champion': 1},
 'Ecuador': {'Group Stage': 44,
  'Round of 32': 394,
  'Round of 16': 268,
  'Quarter-final': 121,
  'Semi-final': 80,
  'Final': 48,
  'Champion': 45},
 'Netherlands': {'Group Stage': 117,
  'Round of 32': 370,
  'Round of 16': 243,
  'Quarter-final': 154,
  'Semi-final': 61,
  'Final': 33,
  'Champion': 22},
 'Japan': {'Group Stage': 69,
  'Round of 32': 340,
  'Round of 16': 235,
  'Quarter-final': 245,
  'Semi-final': 63,
  'Final': 29,
  'Champion': 19},
 'Sweden': {'Group Stage': 406,
  'Round of 32': 382,
  'Round of 16': 142,
  'Quarter-final': 52,
  'Semi-final': 17,
  'Final': 1,
  'Champion': 0},
 'Tunisia': {'Group Stage': 660,
  'Round of 32': 221,
  'Round of 16': 92,
  'Quarter-final': 20,
  'Semi-final': 7,
  'Final': 0,
  'Champion': 0},
 'Belgium': {'Group Stage': 68,
  'Round of 32': 373,
  'Round of 16': 340,
  'Quarter-final': 132,
  'Semi-final': 45,
  'Final': 28,
  'Champion': 14},
 'Egypt': {'Group Stage': 404,
  'Round of 32': 412,
  'Round of 16': 143,
  'Quarter-final': 29,
  'Semi-final': 10,
  'Final': 1,
  'Champion': 1},
 'Iran': {'Group Stage': 227,
  'Round of 32': 518,
  'Round of 16': 192,
  'Quarter-final': 48,
  'Semi-final': 11,
  'Final': 4,
  'Champion': 0},
 'New Zealand': {'Group Stage': 616,
  'Round of 32': 282,
  'Round of 16': 79,
  'Quarter-final': 15,
  'Semi-final': 7,
  'Final': 1,
  'Champion': 0},
 'Spain': {'Group Stage': 0,
  'Round of 32': 86,
  'Round of 16': 171,
  'Quarter-final': 217,
  'Semi-final': 100,
  'Final': 128,
  'Champion': 298},
 'Cape Verde': {'Group Stage': 647,
  'Round of 32': 282,
  'Round of 16': 61,
  'Quarter-final': 9,
  'Semi-final': 1,
  'Final': 0,
  'Champion': 0},
 'Saudi Arabia': {'Group Stage': 575,
  'Round of 32': 326,
  'Round of 16': 84,
  'Quarter-final': 11,
  'Semi-final': 3,
  'Final': 1,
  'Champion': 0},
 'Uruguay': {'Group Stage': 338,
  'Round of 32': 323,
  'Round of 16': 244,
  'Quarter-final': 39,
  'Semi-final': 27,
  'Final': 14,
  'Champion': 15},
 'France': {'Group Stage': 36,
  'Round of 32': 298,
  'Round of 16': 308,
  'Quarter-final': 125,
  'Semi-final': 55,
  'Final': 88,
  'Champion': 90},
 'Senegal': {'Group Stage': 236,
  'Round of 32': 455,
  'Round of 16': 155,
  'Quarter-final': 64,
  'Semi-final': 58,
  'Final': 21,
  'Champion': 11},
 'Norway': {'Group Stage': 261,
  'Round of 32': 346,
  'Round of 16': 202,
  'Quarter-final': 90,
  'Semi-final': 56,
  'Final': 31,
  'Champion': 14},
 'Iraq': {'Group Stage': 740,
  'Round of 32': 202,
  'Round of 16': 45,
  'Quarter-final': 11,
  'Semi-final': 2,
  'Final': 0,
  'Champion': 0},
 'Argentina': {'Group Stage': 14,
  'Round of 32': 260,
  'Round of 16': 231,
  'Quarter-final': 184,
  'Semi-final': 67,
  'Final': 97,
  'Champion': 147},
 'Algeria': {'Group Stage': 427,
  'Round of 32': 322,
  'Round of 16': 158,
  'Quarter-final': 66,
  'Semi-final': 17,
  'Final': 10,
  'Champion': 0},
 'Austria': {'Group Stage': 354,
  'Round of 32': 411,
  'Round of 16': 147,
  'Quarter-final': 49,
  'Semi-final': 29,
  'Final': 6,
  'Champion': 4},
 'Jordan': {'Group Stage': 595,
  'Round of 32': 279,
  'Round of 16': 84,
  'Quarter-final': 27,
  'Semi-final': 11,
  'Final': 3,
  'Champion': 1},
 'Portugal': {'Group Stage': 42,
  'Round of 32': 510,
  'Round of 16': 235,
  'Quarter-final': 110,
  'Semi-final': 47,
  'Final': 36,
  'Champion': 20},
 'DR Congo': {'Group Stage': 508,
  'Round of 32': 352,
  'Round of 16': 103,
  'Quarter-final': 28,
  'Semi-final': 9,
  'Final': 0,
  'Champion': 0},
 'Uzbekistan': {'Group Stage': 520,
  'Round of 32': 288,
  'Round of 16': 118,
  'Quarter-final': 42,
  'Semi-final': 25,
  'Final': 4,
  'Champion': 3},
 'Colombia': {'Group Stage': 241,
  'Round of 32': 333,
  'Round of 16': 183,
  'Quarter-final': 120,
  'Semi-final': 61,
  'Final': 31,
  'Champion': 31},
 'England': {'Group Stage': 34,
  'Round of 32': 346,
  'Round of 16': 335,
  'Quarter-final': 141,
  'Semi-final': 59,
  'Final': 35,
  'Champion': 50},
 'Croatia': {'Group Stage': 66,
  'Round of 32': 298,
  'Round of 16': 201,
  'Quarter-final': 248,
  'Semi-final': 82,
  'Final': 66,
  'Champion': 39},
 'Ghana': {'Group Stage': 554,
  'Round of 32': 356,
  'Round of 16': 69,
  'Quarter-final': 17,
  'Semi-final': 4,
  'Final': 0,
  'Champion': 0},
 'Panama': {'Group Stage': 732,
  'Round of 32': 158,
  'Round of 16': 73,
  'Quarter-final': 22,
  'Semi-final': 10,
  'Final': 4,
  'Champion': 1}}

In [105]:
summary = pd.DataFrame.from_dict(reach_counts, orient='index')
summary = summary[stage_order]
summary = (summary / n_sim * 100).round(1)
summary = summary.sort_values('Champion', ascending=False)
summary

,Group Stage,Round of 32,Round of 16,Quarter-final,Semi-final,Final,Champion
Spain,0.0,8.6,17.1,21.7,10.0,12.8,29.8
Argentina,1.4,26.0,23.1,18.4,6.7,9.7,14.7
France,3.6,29.8,30.8,12.5,5.5,8.8,9.0
Brazil,8.8,31.1,18.0,13.6,12.4,9.7,6.4
England,3.4,34.6,33.5,14.1,5.9,3.5,5.0
Ecuador,4.4,39.4,26.8,12.1,8.0,4.8,4.5
Croatia,6.6,29.8,20.1,24.8,8.2,6.6,3.9
Germany,4.2,38.8,23.7,19.3,6.9,4.0,3.1
Colombia,24.1,33.3,18.3,12.0,6.1,3.1,3.1
Mexico,1.1,35.4,24.9,21.6,12.6,2.1,2.3
Netherlands,11.7,37.0,24.3,15.4,6.1,3.3,2.2
Portugal,4.2,51.0,23.5,11.0,4.7,3.6,2.0
Japan,6.9,34.0,23.5,24.5,6.3,2.9,1.9
Uruguay,33.8,32.3,24.4,3.9,2.7,1.4,1.5
Switzerland,2.2,45.5,23.8,13.8,11.2,2.0,1.5
Belgium,6.8,37.3,34.0,13.2,4.5,2.8,1.4
Norway,26.1,34.6,20.2,9.0,5.6,3.1,1.4
Türkiye,23.0,34.4,19.1,11.9,8.9,1.6,1.1
Senegal,23.6,45.5,15.5,6.4,5.8,2.1,1.1
Morocco,11.4,40.2,28.1,9.8,7.8,2.0,0.7
Paraguay,39.3,28.1,19.2,6.9,5.1,0.8,0.6
USA,20.8,46.9,18.3,5.8,5.7,2.0,0.5
Austria,35.4,41.1,14.7,4.9,2.9,0.6,0.4
Uzbekistan,52.0,28.8,11.8,4.2,2.5,0.4,0.3
Canada,2.5,46.2,28.9,13.1,8.4,0.6,0.3
Australia,40.0,29.1,16.3,8.1,5.4,0.8,0.3
South Korea,25.8,42.9,18.6,7.6,4.0,0.9,0.2
Scotland,65.1,20.5,7.7,3.8,2.4,0.3,0.2
Czechia,25.3,42.1,20.3,7.7,3.7,0.7,0.2
Ivory Coast,23.0,52.1,16.4,6.1,1.9,0.4,0.1
Jordan,59.5,27.9,8.4,2.7,1.1,0.3,0.1
Panama,73.2,15.8,7.3,2.2,1.0,0.4,0.1
Egypt,40.4,41.2,14.3,2.9,1.0,0.1,0.1
South Africa,78.2,16.8,3.5,1.3,0.2,0.0,0.0
Qatar,91.3,7.0,1.3,0.4,0.0,0.0,0.0
Bosnia and Herzegovina,49.5,37.8,8.8,3.2,0.7,0.0,0.0
Haiti,42.8,46.7,7.9,2.2,0.3,0.1,0.0
Sweden,40.6,38.2,14.2,5.2,1.7,0.1,0.0
Tunisia,66.0,22.1,9.2,2.0,0.7,0.0,0.0
Curaçao,92.6,6.1,1.1,0.2,0.0,0.0,0.0
Saudi Arabia,57.5,32.6,8.4,1.1,0.3,0.1,0.0
Cape Verde,64.7,28.2,6.1,0.9,0.1,0.0,0.0
Iran,22.7,51.8,19.2,4.8,1.1,0.4,0.0
New Zealand,61.6,28.2,7.9,1.5,0.7,0.1,0.0
Algeria,42.7,32.2,15.8,6.6,1.7,1.0,0.0
Iraq,74.0,20.2,4.5,1.1,0.2,0.0,0.0
DR Congo,50.8,35.2,10.3,2.8,0.9,0.0,0.0
Ghana,55.4,35.6,6.9,1.7,0.4,0.0,0.0

In [106]:
print(train['elo_diff'].describe())

for diff in [0, 100, 200, 300, 400, 500, 600]:
    X_test = pd.DataFrame({'elo_diff': [diff], 'neutral': [True]})
    lh = model_home.predict(X_test)[0]
    la = model_away.predict(X_test)[0]
    print(diff, round(lh, 2), round(la, 2))

count    5518.000000
mean        0.179594
std       208.609509
min      -903.000000
25%      -136.000000
50%         4.500000
75%       134.750000
max       874.000000
Name: elo_diff, dtype: float64
0 1.31 0.81
100 1.86 0.82
200 1.41 1.09
300 1.91 0.63
400 2.74 0.77
500 3.55 0.67
600 2.59 0.59